### ISSUE TITLE
Provide local versions of images

### ISSUE THREAD

**Issue by alangrafu** [basilioss/obsidian-scrapers#1]
Something really nice would be to support local images that can be downloaded and used in these scripts.

I tried adding the following code to goodreads.js but for some reason I got an `ERR_CONNECTION_REFUSED` error

First line:
```javascript
fs = require('fs');
```

Later in the case switch:
```javascript
    case "coverLocal":
      let coverUrl = $("img[id='coverImage']").src || "";
      let image = await tp.obsidian.request({ coverUrl });
      url_parts = coverUrl.split(".");
      let extension  = url_parts[url_parts.length - 1]; // Assumes there is an extension, TODO: deal with that
      let filename = new Date().getTime().toString() + "." + extension;
      fs.writeFile(filename, image);
      return "[["+filename+"]]";
```

**Comment by basilioss** [comment]
There is [Local images](https://github.com/aleksey-rezvov/obsidian-local-images) plugin, but maybe I'll try to implement it later.
Upd: There is also [Local Images Plus](https://github.com/Sergei-Korneev/obsidian-local-images-plus) plugin.
