### ISSUE TITLE
Provide an option to get full text of YouTube video, not just the short description

### ISSUE THREAD

**Issue by slappycat2** [basilioss/obsidian-scrapers#2]
The Description parameter only pull the truncated, short description. My JS is not good. Is there any way to get the full text from a video?

BTW: I really love this plugin!

**Comment by slappycat2** [comment]
Hi, @basilioss,
Is this possible? It would be very useful for quickly capturing YouTube video highlights and timestamps without having to watch them in their entirety. Like say videos that show recipes to be used later.  I've tried but my JS is a little weak.

**Comment by basilioss** [comment]
Hi, you can make an update with `git pull` or simply redownload the repo to use `descriptionFull` option now
