### ISSUE TITLE
Getting Video ID for YouTube doesn't work.

### ISSUE THREAD

**Issue by LightTemplar** [basilioss/obsidian-scrapers#4]
If I put `id: <% tp.user.youtube('id', tp, doc) %>` into template, it doesn't work and in the developers console I see following message:
```
Templater Error: Template parsing error, aborting. 
 Cannot read properties of null (reading 'content')
log_error	@	plugin:templater-obsidian:61
errorWrapper	@	plugin:templater-obsidian:81
await in errorWrapper (async)		
append_template_to_active_file	@	plugin:templater-obsidian:3700
onChooseItem	@	plugin:templater-obsidian:2391
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
e.onSuggestionClick	@	app.js:1
s	@	enhance.js:1
```

Could you please check?

**Comment by basilioss** [comment]
Thanks for reporting this issue, it should be fixed now. To update it, change the current working directory in the terminal to `/path/to/obsidian-scrapers` with `cd /path/to/obsidian-scrapers` and run `git pull` or just redownload the repository.
